const qualificationOptions: any = [
  { label: "High School Diploma", value: "high_school" },
  { label: "Associate Degree", value: "associate" },
  { label: "Bachelor's Degree", value: "bachelor" },
  { label: "Master's Degree", value: "master" },
  { label: "Doctorate or Higher", value: "doctorate" },

  { label: "Other ", value: "other" },
];

const skillsAndExpertiseOptions: any = [
  { label: "Electrician", value: "electrician" },
  { label: "Plumbing", value: "plumbing" },
  { label: "Carpentry", value: "carpentry" },
  { label: "Landscaping", value: "landscaping" },
  { label: "Welding", value: "welding" },
];
const JobType: any = [
  { label: "Full-time", value: "full-time" },
  { label: "Part-time", value: "part-time" },
  { label: "Contract", value: "contract" },
];
export const formdata: any = [
  {
    title: "Full Name",
    description: "Enter your full legal name",
    tag: "text",
    required: true,
    name: "full_name",
    type: "text",
  },
  {
    title: "Contact Number",
    description: "Enter your contact number",
    tag: "number",
    required: true,
    name: "mobile_number",
    type: "number",
  },
  {
    title: "Email Address",
    description: "Enter your email address",
    tag: "text",
    required: true,
    name: "email",
    type: "text",
  },
  {
    title: "Address",
    description: "Enter your current address",
    tag: "text",
    required: true,
    name: "residential_address",
    type: "text",
  },
  {
    title: "Date of Birth",
    description: "Select your date of birth",
    tag: "date",
    required: false,
    name: "date_of_birth",
    type: "date",
  },
  {
    title: "Qualifications",
    description: "Enter your highest academic qualifications",
    tag: "select",
    required: false,
    name: "qualifications",
    type: "text",
    options: qualificationOptions,
  },

  {
    title: "Skills and Expertise",
    description: "Add tags for your skills such as electrician, plumbing, etc.",
    tag: "select",
    required: true,
    name: "skills_and_expertise",
    type: "text",
    options: skillsAndExpertiseOptions,
  },
  {
    title: "Years of Experience",
    description: "Enter how many years of experience you have in your field",
    tag: "number",
    required: true,
    name: "experience_in_years",
    type: "number",
  },

  {
    title: "Work Location",
    description: "Specify your preferred work location(s)",
    tag: "text",
    required: true,
    name: "work_location",
    type: "text",
  },
  {
    title: "Latitude",
    description: "Enter your latitude",
    tag: "number",
    required: true,
    name: "latitude",
    type: "number",
  },
  {
    title: "Longitude",
    description: "Enter your longitude",
    tag: "number",
    required: true,
    name: "longitude",
    type: "number",
  },
  {
    title: "Job Type",
    description: "Select the type of job you are looking for",
    tag: "select",
    required: true,
    name: "job_type",
    type: "select",
    options: JobType,
  },
  {
    title: "Expected Salary/hr",
    description: "Enter your expected hourly salary",
    tag: "number",
    required: true,
    name: "hourly_salary",
    type: "number",
  },
  {
    title: "Identification Proof",
    description: "Upload a government issued ID",
    tag: "file",
    required: false,
    name: "identification_proof",
    type: "file",
  },
  {
    title: "Address Proof",
    description: "Upload a document to prove your address",
    tag: "file",
    required: false,
    name: "addressproof",
    type: "file",
  },
  {
    title: "PAN Card",
    description: "Upload your PAN card image",
    tag: "file",
    required: false,
    name: "pan_proof",
    type: "file",
  },
  {
    title: "Profile Image",
    description: "Upload your profile image",
    tag: "file",
    required: false,
    name: "profilePic",
    type: "file",
  },
  {
    title: "Certifications and Licenses",
    description: "Upload any certifications or licenses you have",
    tag: "file",
    required: false,
    name: "licence_and_certificates",
    type: "file",
  },
];
